NAME=socketpipe
SSH=plink
VERSION=1.10
DIR=$(NAME)-$(VERSION)
SRC_BALL=$(DIR).tar.gz
DOC=$(NAME).txt $(NAME).pdf $(NAME).html
WEBDIR=/cygdrive/c/dds/pubs/web/home/sw/unix/$(NAME)

$(NAME): $(NAME).c
	$(CC) $(CFLAGS) -o $@ $?

$(NAME).ps: $(NAME).1
	groff -man -Tps <$? > $@

$(NAME).txt: $(NAME).1
	groff -man -Tascii <$? | col -b > $@

$(NAME).pdf: $(NAME).ps
	ps2pdf $? $@

$(NAME).html: $(NAME).1
	groff -mhtml -Thtml -man <$? | sed -e 's/&minus;/-/g;s/&bull;/\&#8226;/g' >$@

src-tarball: $(SRC_BALL)

$(SRC_BALL): $(DOC) $(NAME).1 $(NAME).c Makefile
	-cmd /c rd /q/s "$(DIR)"
	mkdir $(DIR)
	cp Makefile $(NAME).1 $(NAME).c $(NAME).pdf $(NAME).html $(NAME).txt ChangeLog.txt $(DIR)
	for i in $(NAME).1 $(NAME).c Makefile ; do dos2unix $(DIR)/$$i ; done
	tar czvf $(SRC_BALL) $(DIR)
	cmd /c rd /q/s "$(DIR)"

socketpipe.exe: socketpipe.c

web: $(DOC) $(SRC_BALL) socketpipe.exe
	-chmod 666 $(WEBDIR)/$(NAME).c $(WEBDIR)/$(NAME).1
	cp -f $(SRC_BALL) $(NAME).c $(NAME).1 $(NAME).pdf $(NAME).html $(NAME).jpg ChangeLog.txt socketpipe.exe $(WEBDIR)
	sed -e "s/VERSION/${VERSION}/" index.html >${WEBDIR}/index.html
